### ISSUE TITLE
Unable to find the classpath

### ISSUE THREAD

**Issue by rosedawson75** [DreamCloudProject/WIND#1]
Hi Sir,

I am trying to migtrate ant script to gradle script in out ATG project.

I downloaded your code to test and understand.

When I am trying to execute "gradle build" I am getting following exception : 

[error.txt](https://github.com/DreamCloudProject/WIND/files/375375/error.txt)

I tried to print "println sourceSets.main.compileClasspath" : the classpath is empty

Can you please help me here please?

**Comment by DreamCloudProject** [comment]
Hello,

Did you do the step 3 in guide to install?

https://github.com/DreamCloudProject/WIND/tree/master/install

**Comment by rosedawson75** [comment]
Yes .

**Comment by DreamCloudProject** [comment]
clean cleanEars :Storefront:build generateClassesJars generateConfigJars generateResourcesJars assembleAllEars

Could you check this list of commands together?

**Comment by rosedawson75** [comment]
Ha Still facing same issue. 

I think some how it is not picking up build.gradle file which is inside Commerce->Assmbler directory.

**Comment by DreamCloudProject** [comment]
Please check file names of these jars in your environment:

System.getenv("ATG_ROOT")+'/DAF/Endeca/Assembler/lib/endeca_navigation-6.5.1.jar',
System.getenv("ATG_ROOT")+'/DAF/Endeca/Assembler/lib/endeca_assembler_core-11.1.0.jar',
System.getenv("ATG_ROOT")+'/DAF/Endeca/Assembler/lib/endeca_assembler_navigation-11.1.0.jar')

**Comment by rosedawson75** [comment]
Hi , 

Its working now.

I used below code in build.gradle in Commerce module:+1: //----------------------------------
/**
- Build the dynamo classpath and make it available as a script variable.
  */
  task("setDynamoClasspath", description: "Configuration task to set the Dynamo classpath.",
  group: "CSA Custom") {
  
  // Define a task that sets a given property to the classpath 
  // required by a given set of Dynamo modules, by examining the 
  // module manifests.
  ant.taskdef(name:"dynamoclasspath",
              classname: "atg.applauncher.taskdef.DynamoClasspathTask",
              classpath: dynamoHome + "/lib/launcher.jar")
  
  // Execute the dynamoclasspath task to generate the classpath.
  ant.dynamoclasspath(classpathproperty: "dynamo.classpath",
                      dynamoroot: dynamoHome + "/../",
                      modules: 'BCI.Commerce')
  
  project.ext.dynamoclasspath = ant.properties["dynamo.classpath"]
  }

**Comment by rosedawson75** [comment]
Thanks for your help.

**Comment by DreamCloudProject** [comment]
You are welcome. Thanks for the response!
